
source 'https://rubygems.org'

gem 'rails', '~> 5.1.4'
gem 'puma', '~> 4.3'
gem 'redis', '~> 3.2'
gem 'pg', '~> 0.18.3'
gem 'bcrypt', '~> 3.1.7'

# PubSub
gem 'wisper', '~> 2.0'

# Error / Perfomance reporting
gem 'bugsnag'
gem 'newrelic_rpm', '~> 3.18.1'

gem 'countries', '~> 1.2.2'

# Logging
gem 'logstash-event'
gem 'lograge'