
source 'https://rubygems.org'

gem 'rails', '5.2.1'
gem 'puma'
gem 'pg', '~> 1.1.3'
gem 'redis', '~> 4.0.2'
gem 'redis-rails', '~> 5.0', '>= 5.0.2'
gem 'bcrypt', '~> 3.1.12'
gem 'countries', '~> 2.1.4'

# PubSub
gem 'wisper', '~> 2.0'

# Error / Perfomance reporting
gem 'bugsnag'

# Logging
gem 'logstash-event'
gem 'lograge'
